// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bots.sql

package dbgen

import (
	"context"
)

const createBot = `-- name: CreateBot :one
INSERT INTO bots (owner_id, telegram_id, name, username, encrypted_token, has_webhook, pending_updates, verified_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
RETURNING id, telegram_id, name, username, has_webhook, pending_updates, verified_at
`

type CreateBotParams struct {
	OwnerID        int64
	TelegramID     int64
	Name           string
	Username       string
	EncryptedToken []byte
	HasWebhook     int64
	PendingUpdates int64
	VerifiedAt     int64
}

type CreateBotRow struct {
	ID             int64
	TelegramID     int64
	Name           string
	Username       string
	HasWebhook     int64
	PendingUpdates int64
	VerifiedAt     int64
}

func (q *Queries) CreateBot(ctx context.Context, arg CreateBotParams) (CreateBotRow, error) {
	row := q.db.QueryRowContext(ctx, createBot,
		arg.OwnerID,
		arg.TelegramID,
		arg.Name,
		arg.Username,
		arg.EncryptedToken,
		arg.HasWebhook,
		arg.PendingUpdates,
		arg.VerifiedAt,
	)
	var i CreateBotRow
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Name,
		&i.Username,
		&i.HasWebhook,
		&i.PendingUpdates,
		&i.VerifiedAt,
	)
	return i, err
}

const getOwnerBot = `-- name: GetOwnerBot :one
SELECT id, telegram_id, name, username, has_webhook, pending_updates, verified_at
FROM bots WHERE owner_id = ?1 AND id = ?2
`

type GetOwnerBotParams struct {
	OwnerID int64
	ID      int64
}

type GetOwnerBotRow struct {
	ID             int64
	TelegramID     int64
	Name           string
	Username       string
	HasWebhook     int64
	PendingUpdates int64
	VerifiedAt     int64
}

func (q *Queries) GetOwnerBot(ctx context.Context, arg GetOwnerBotParams) (GetOwnerBotRow, error) {
	row := q.db.QueryRowContext(ctx, getOwnerBot, arg.OwnerID, arg.ID)
	var i GetOwnerBotRow
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Name,
		&i.Username,
		&i.HasWebhook,
		&i.PendingUpdates,
		&i.VerifiedAt,
	)
	return i, err
}

const listOwnerBots = `-- name: ListOwnerBots :many
SELECT id, telegram_id, name, username, has_webhook, pending_updates, verified_at
FROM bots WHERE owner_id = ?1 ORDER BY id DESC
`

type ListOwnerBotsRow struct {
	ID             int64
	TelegramID     int64
	Name           string
	Username       string
	HasWebhook     int64
	PendingUpdates int64
	VerifiedAt     int64
}

func (q *Queries) ListOwnerBots(ctx context.Context, ownerID int64) ([]ListOwnerBotsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOwnerBots, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnerBotsRow{}
	for rows.Next() {
		var i ListOwnerBotsRow
		if err := rows.Scan(
			&i.ID,
			&i.TelegramID,
			&i.Name,
			&i.Username,
			&i.HasWebhook,
			&i.PendingUpdates,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
