// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bots.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createBot = `-- name: CreateBot :one
INSERT INTO bots (owner_id, telegram_id, name, username, encrypted_token, has_webhook, pending_updates, verified_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
RETURNING id, telegram_id, name, username, has_webhook, pending_updates, verified_at
`

type CreateBotParams struct {
	OwnerID        int64
	TelegramID     sql.NullInt64
	Name           string
	Username       string
	EncryptedToken []byte
	HasWebhook     int64
	PendingUpdates int64
	VerifiedAt     int64
}

type CreateBotRow struct {
	ID             int64
	TelegramID     sql.NullInt64
	Name           string
	Username       string
	HasWebhook     int64
	PendingUpdates int64
	VerifiedAt     int64
}

func (q *Queries) CreateBot(ctx context.Context, arg CreateBotParams) (CreateBotRow, error) {
	row := q.db.QueryRowContext(ctx, createBot,
		arg.OwnerID,
		arg.TelegramID,
		arg.Name,
		arg.Username,
		arg.EncryptedToken,
		arg.HasWebhook,
		arg.PendingUpdates,
		arg.VerifiedAt,
	)
	var i CreateBotRow
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Name,
		&i.Username,
		&i.HasWebhook,
		&i.PendingUpdates,
		&i.VerifiedAt,
	)
	return i, err
}

const createUnconnectedBot = `-- name: CreateUnconnectedBot :one
INSERT INTO bots (owner_id, name, username, encrypted_token, has_webhook, pending_updates, verified_at)
VALUES (?1, ?2, '', X'', 0, 0, 0)
RETURNING id
`

type CreateUnconnectedBotParams struct {
	OwnerID int64
	Name    string
}

func (q *Queries) CreateUnconnectedBot(ctx context.Context, arg CreateUnconnectedBotParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUnconnectedBot, arg.OwnerID, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteOwnerUnconnectedBot = `-- name: DeleteOwnerUnconnectedBot :execrows
DELETE FROM bots WHERE owner_id = ?1 AND id = ?2 AND telegram_id IS NULL
`

type DeleteOwnerUnconnectedBotParams struct {
	OwnerID int64
	ID      int64
}

func (q *Queries) DeleteOwnerUnconnectedBot(ctx context.Context, arg DeleteOwnerUnconnectedBotParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOwnerUnconnectedBot, arg.OwnerID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBotPaused = `-- name: GetBotPaused :one
SELECT paused FROM bots WHERE id = ?1
`

func (q *Queries) GetBotPaused(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBotPaused, id)
	var paused int64
	err := row.Scan(&paused)
	return paused, err
}

const getOwnerBot = `-- name: GetOwnerBot :one
SELECT bots.id, bots.telegram_id, bots.name, bots.username, bots.has_webhook, bots.pending_updates, bots.verified_at, bots.webhook_is_piko, bots.paused,
CAST(bots.telegram_id IS NULL AS INTEGER) AS unconnected,
CAST(bots.telegram_id IS NOT NULL AND length(bots.encrypted_token) = 0 AS INTEGER) AS disconnected,
CAST(COALESCE((SELECT MAX(version) FROM bot_publications WHERE bot_id = bots.id), 0) AS INTEGER) AS published_version,
CAST(COALESCE((SELECT state FROM bot_delivery WHERE bot_id = bots.id), 'inactive') AS TEXT) AS delivery_state,
CAST(COALESCE((SELECT mode FROM bot_delivery WHERE bot_id = bots.id), '') AS TEXT) AS delivery_mode,
CAST(COALESCE((SELECT worker_error FROM bot_delivery WHERE bot_id = bots.id), 0) OR EXISTS(SELECT 1 FROM bot_updates WHERE bot_id = bots.id AND ((complete = 0 AND attempts > 0) OR terminal_failure = 1)) AS INTEGER) AS delivery_error
FROM bots WHERE bots.owner_id = ?1 AND bots.id = ?2
`

type GetOwnerBotParams struct {
	OwnerID int64
	ID      int64
}

type GetOwnerBotRow struct {
	ID               int64
	TelegramID       sql.NullInt64
	Name             string
	Username         string
	HasWebhook       int64
	PendingUpdates   int64
	VerifiedAt       int64
	WebhookIsPiko    int64
	Paused           int64
	Unconnected      int64
	Disconnected     int64
	PublishedVersion int64
	DeliveryState    string
	DeliveryMode     string
	DeliveryError    int64
}

func (q *Queries) GetOwnerBot(ctx context.Context, arg GetOwnerBotParams) (GetOwnerBotRow, error) {
	row := q.db.QueryRowContext(ctx, getOwnerBot, arg.OwnerID, arg.ID)
	var i GetOwnerBotRow
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Name,
		&i.Username,
		&i.HasWebhook,
		&i.PendingUpdates,
		&i.VerifiedAt,
		&i.WebhookIsPiko,
		&i.Paused,
		&i.Unconnected,
		&i.Disconnected,
		&i.PublishedVersion,
		&i.DeliveryState,
		&i.DeliveryMode,
		&i.DeliveryError,
	)
	return i, err
}

const listOwnerBots = `-- name: ListOwnerBots :many
SELECT bots.id, bots.telegram_id, bots.name, bots.username, bots.has_webhook, bots.pending_updates, bots.verified_at, bots.webhook_is_piko, bots.paused,
CAST(bots.telegram_id IS NULL AS INTEGER) AS unconnected,
CAST(bots.telegram_id IS NOT NULL AND length(bots.encrypted_token) = 0 AS INTEGER) AS disconnected,
CAST(COALESCE((SELECT MAX(version) FROM bot_publications WHERE bot_id = bots.id), 0) AS INTEGER) AS published_version,
CAST(COALESCE((SELECT state FROM bot_delivery WHERE bot_id = bots.id), 'inactive') AS TEXT) AS delivery_state,
CAST(COALESCE((SELECT mode FROM bot_delivery WHERE bot_id = bots.id), '') AS TEXT) AS delivery_mode,
CAST(COALESCE((SELECT worker_error FROM bot_delivery WHERE bot_id = bots.id), 0) OR EXISTS(SELECT 1 FROM bot_updates WHERE bot_id = bots.id AND ((complete = 0 AND attempts > 0) OR terminal_failure = 1)) AS INTEGER) AS delivery_error
FROM bots WHERE bots.owner_id = ?1 ORDER BY bots.id DESC
`

type ListOwnerBotsRow struct {
	ID               int64
	TelegramID       sql.NullInt64
	Name             string
	Username         string
	HasWebhook       int64
	PendingUpdates   int64
	VerifiedAt       int64
	WebhookIsPiko    int64
	Paused           int64
	Unconnected      int64
	Disconnected     int64
	PublishedVersion int64
	DeliveryState    string
	DeliveryMode     string
	DeliveryError    int64
}

func (q *Queries) ListOwnerBots(ctx context.Context, ownerID int64) ([]ListOwnerBotsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOwnerBots, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnerBotsRow{}
	for rows.Next() {
		var i ListOwnerBotsRow
		if err := rows.Scan(
			&i.ID,
			&i.TelegramID,
			&i.Name,
			&i.Username,
			&i.HasWebhook,
			&i.PendingUpdates,
			&i.VerifiedAt,
			&i.WebhookIsPiko,
			&i.Paused,
			&i.Unconnected,
			&i.Disconnected,
			&i.PublishedVersion,
			&i.DeliveryState,
			&i.DeliveryMode,
			&i.DeliveryError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOwnerBotPaused = `-- name: SetOwnerBotPaused :execrows
UPDATE bots SET paused = ?3 WHERE bots.owner_id = ?1 AND bots.id = ?2
AND bots.telegram_id IS NOT NULL AND length(bots.encrypted_token) > 0
AND EXISTS (SELECT 1 FROM bot_delivery WHERE bot_id = ?2 AND state = 'active' AND mode = ?4)
AND EXISTS (SELECT 1 FROM bot_publications WHERE bot_id = ?2)
`

type SetOwnerBotPausedParams struct {
	OwnerID int64
	ID      int64
	Paused  int64
	Mode    string
}

func (q *Queries) SetOwnerBotPaused(ctx context.Context, arg SetOwnerBotPausedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setOwnerBotPaused,
		arg.OwnerID,
		arg.ID,
		arg.Paused,
		arg.Mode,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
