// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: builder.sql

package dbgen

import (
	"context"
)

const appendOwnerBuilderMessage = `-- name: AppendOwnerBuilderMessage :one
INSERT INTO builder_messages (chat_id, sequence, role, content, created_at)
SELECT c.id, COALESCE((SELECT MAX(m.sequence) FROM builder_messages m WHERE m.chat_id = c.id), 0) + 1,
?1, ?2, ?3
FROM builder_chats c JOIN bots b ON b.id = c.bot_id
WHERE b.owner_id = ?4 AND b.id = ?5 AND c.id = ?6
RETURNING chat_id, sequence, role, content, created_at
`

type AppendOwnerBuilderMessageParams struct {
	Role      string
	Content   string
	CreatedAt int64
	OwnerID   int64
	BotID     int64
	ChatID    int64
}

func (q *Queries) AppendOwnerBuilderMessage(ctx context.Context, arg AppendOwnerBuilderMessageParams) (BuilderMessage, error) {
	row := q.db.QueryRowContext(ctx, appendOwnerBuilderMessage,
		arg.Role,
		arg.Content,
		arg.CreatedAt,
		arg.OwnerID,
		arg.BotID,
		arg.ChatID,
	)
	var i BuilderMessage
	err := row.Scan(
		&i.ChatID,
		&i.Sequence,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createOwnerBuilderChat = `-- name: CreateOwnerBuilderChat :one
INSERT INTO builder_chats (bot_id, title, created_at, updated_at)
SELECT b.id, ?1, ?2, ?2
FROM bots b WHERE b.owner_id = ?3 AND b.id = ?4
RETURNING id, bot_id, title, created_at, updated_at
`

type CreateOwnerBuilderChatParams struct {
	Title     string
	CreatedAt int64
	OwnerID   int64
	BotID     int64
}

func (q *Queries) CreateOwnerBuilderChat(ctx context.Context, arg CreateOwnerBuilderChatParams) (BuilderChat, error) {
	row := q.db.QueryRowContext(ctx, createOwnerBuilderChat,
		arg.Title,
		arg.CreatedAt,
		arg.OwnerID,
		arg.BotID,
	)
	var i BuilderChat
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOwnerBuilderChat = `-- name: DeleteOwnerBuilderChat :execrows
DELETE FROM builder_chats WHERE builder_chats.id = ?1 AND builder_chats.bot_id = ?2
AND EXISTS (SELECT 1 FROM bots b WHERE b.id = builder_chats.bot_id AND b.owner_id = ?3)
`

type DeleteOwnerBuilderChatParams struct {
	ChatID  int64
	BotID   int64
	OwnerID int64
}

func (q *Queries) DeleteOwnerBuilderChat(ctx context.Context, arg DeleteOwnerBuilderChatParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOwnerBuilderChat, arg.ChatID, arg.BotID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getOwnerBuilderChat = `-- name: GetOwnerBuilderChat :one
SELECT c.id, c.bot_id, c.title, c.created_at, c.updated_at FROM builder_chats c JOIN bots b ON b.id = c.bot_id
WHERE b.owner_id = ?1 AND b.id = ?2 AND c.id = ?3
`

type GetOwnerBuilderChatParams struct {
	OwnerID int64
	BotID   int64
	ChatID  int64
}

func (q *Queries) GetOwnerBuilderChat(ctx context.Context, arg GetOwnerBuilderChatParams) (BuilderChat, error) {
	row := q.db.QueryRowContext(ctx, getOwnerBuilderChat, arg.OwnerID, arg.BotID, arg.ChatID)
	var i BuilderChat
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOwnerBuilderChats = `-- name: ListOwnerBuilderChats :many
SELECT c.id, c.bot_id, c.title, c.created_at, c.updated_at FROM builder_chats c JOIN bots b ON b.id = c.bot_id
WHERE b.owner_id = ?1 AND b.id = ?2
ORDER BY c.id DESC
`

type ListOwnerBuilderChatsParams struct {
	OwnerID int64
	BotID   int64
}

func (q *Queries) ListOwnerBuilderChats(ctx context.Context, arg ListOwnerBuilderChatsParams) ([]BuilderChat, error) {
	rows, err := q.db.QueryContext(ctx, listOwnerBuilderChats, arg.OwnerID, arg.BotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BuilderChat{}
	for rows.Next() {
		var i BuilderChat
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnerBuilderMessages = `-- name: ListOwnerBuilderMessages :many
SELECT m.chat_id, m.sequence, m.role, m.content, m.created_at FROM builder_messages m
JOIN builder_chats c ON c.id = m.chat_id JOIN bots b ON b.id = c.bot_id
WHERE b.owner_id = ?1 AND b.id = ?2 AND c.id = ?3
ORDER BY m.sequence
`

type ListOwnerBuilderMessagesParams struct {
	OwnerID int64
	BotID   int64
	ChatID  int64
}

func (q *Queries) ListOwnerBuilderMessages(ctx context.Context, arg ListOwnerBuilderMessagesParams) ([]BuilderMessage, error) {
	rows, err := q.db.QueryContext(ctx, listOwnerBuilderMessages, arg.OwnerID, arg.BotID, arg.ChatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BuilderMessage{}
	for rows.Next() {
		var i BuilderMessage
		if err := rows.Scan(
			&i.ChatID,
			&i.Sequence,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchOwnerBuilderChat = `-- name: TouchOwnerBuilderChat :exec
UPDATE builder_chats SET updated_at = ?1
WHERE builder_chats.id = ?2 AND builder_chats.bot_id = ?3
AND EXISTS (SELECT 1 FROM bots b WHERE b.id = builder_chats.bot_id AND b.owner_id = ?4)
`

type TouchOwnerBuilderChatParams struct {
	UpdatedAt int64
	ChatID    int64
	BotID     int64
	OwnerID   int64
}

func (q *Queries) TouchOwnerBuilderChat(ctx context.Context, arg TouchOwnerBuilderChatParams) error {
	_, err := q.db.ExecContext(ctx, touchOwnerBuilderChat,
		arg.UpdatedAt,
		arg.ChatID,
		arg.BotID,
		arg.OwnerID,
	)
	return err
}
