// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: builder_runs.sql

package dbgen

import (
	"context"
	"database/sql"
)

const accountOwnerBuilderCall = `-- name: AccountOwnerBuilderCall :exec
UPDATE builder_calls SET input_tokens=?1,output_tokens=?2,
total_tokens=?3,cost=?4
WHERE run_id=?5 AND sequence=?6
AND EXISTS (SELECT 1 FROM builder_runs r WHERE r.id=builder_calls.run_id AND r.owner_id=?7)
`

type AccountOwnerBuilderCallParams struct {
	InputTokens  sql.NullInt64
	OutputTokens sql.NullInt64
	TotalTokens  sql.NullInt64
	Cost         sql.NullString
	RunID        int64
	Sequence     int64
	OwnerID      int64
}

func (q *Queries) AccountOwnerBuilderCall(ctx context.Context, arg AccountOwnerBuilderCallParams) error {
	_, err := q.db.ExecContext(ctx, accountOwnerBuilderCall,
		arg.InputTokens,
		arg.OutputTokens,
		arg.TotalTokens,
		arg.Cost,
		arg.RunID,
		arg.Sequence,
		arg.OwnerID,
	)
	return err
}

const activeOwnerBuilderBot = `-- name: ActiveOwnerBuilderBot :one
SELECT COUNT(*) FROM builder_runs WHERE owner_id = ?1 AND bot_id = ?2 AND status = 'running'
`

type ActiveOwnerBuilderBotParams struct {
	OwnerID int64
	BotID   sql.NullInt64
}

func (q *Queries) ActiveOwnerBuilderBot(ctx context.Context, arg ActiveOwnerBuilderBotParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, activeOwnerBuilderBot, arg.OwnerID, arg.BotID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const activeOwnerBuilderChat = `-- name: ActiveOwnerBuilderChat :one
SELECT COUNT(*) FROM builder_runs WHERE owner_id = ?1 AND chat_id = ?2 AND status = 'running'
`

type ActiveOwnerBuilderChatParams struct {
	OwnerID int64
	ChatID  sql.NullInt64
}

func (q *Queries) ActiveOwnerBuilderChat(ctx context.Context, arg ActiveOwnerBuilderChatParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, activeOwnerBuilderChat, arg.OwnerID, arg.ChatID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const admitOwnerBuilderRun = `-- name: AdmitOwnerBuilderRun :one
INSERT INTO builder_runs (owner_id,bot_id,chat_id,day,model,draft_revision,status,created_at,lease_until,request_sequence)
SELECT b.owner_id,b.id,c.id,?1,?2,?3,'running',?4,?5,?6
FROM builder_chats c JOIN bots b ON b.id=c.bot_id
WHERE b.owner_id=?7 AND b.id=?8 AND c.id=?9
RETURNING id, owner_id, bot_id, chat_id, day, model, draft_revision, status, created_at, lease_until, finished_at, model_calls, request_sequence
`

type AdmitOwnerBuilderRunParams struct {
	Day             string
	Model           string
	DraftRevision   int64
	CreatedAt       int64
	LeaseUntil      int64
	RequestSequence sql.NullInt64
	OwnerID         int64
	BotID           int64
	ChatID          int64
}

func (q *Queries) AdmitOwnerBuilderRun(ctx context.Context, arg AdmitOwnerBuilderRunParams) (BuilderRun, error) {
	row := q.db.QueryRowContext(ctx, admitOwnerBuilderRun,
		arg.Day,
		arg.Model,
		arg.DraftRevision,
		arg.CreatedAt,
		arg.LeaseUntil,
		arg.RequestSequence,
		arg.OwnerID,
		arg.BotID,
		arg.ChatID,
	)
	var i BuilderRun
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.BotID,
		&i.ChatID,
		&i.Day,
		&i.Model,
		&i.DraftRevision,
		&i.Status,
		&i.CreatedAt,
		&i.LeaseUntil,
		&i.FinishedAt,
		&i.ModelCalls,
		&i.RequestSequence,
	)
	return i, err
}

const countOwnerBuilderDay = `-- name: CountOwnerBuilderDay :one
SELECT COUNT(*) FROM builder_runs WHERE owner_id = ?1 AND day = ?2
`

type CountOwnerBuilderDayParams struct {
	OwnerID int64
	Day     string
}

func (q *Queries) CountOwnerBuilderDay(ctx context.Context, arg CountOwnerBuilderDayParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOwnerBuilderDay, arg.OwnerID, arg.Day)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const finishOwnerBuilderRun = `-- name: FinishOwnerBuilderRun :execrows
UPDATE builder_runs SET status=?1,finished_at=?2
WHERE builder_runs.id=?3 AND builder_runs.owner_id=?4 AND status='running'
AND lease_until > ?5
AND EXISTS (SELECT 1 FROM builder_chats c JOIN bots b ON b.id=c.bot_id
    WHERE c.id=builder_runs.chat_id AND b.id=builder_runs.bot_id AND b.owner_id=builder_runs.owner_id)
`

type FinishOwnerBuilderRunParams struct {
	Status     string
	FinishedAt sql.NullInt64
	RunID      int64
	OwnerID    int64
	Now        int64
}

func (q *Queries) FinishOwnerBuilderRun(ctx context.Context, arg FinishOwnerBuilderRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishOwnerBuilderRun,
		arg.Status,
		arg.FinishedAt,
		arg.RunID,
		arg.OwnerID,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLatestOwnerBuilderRunStatus = `-- name: GetLatestOwnerBuilderRunStatus :one
SELECT r.id,r.status FROM builder_runs r JOIN bots b ON b.id=r.bot_id
WHERE r.owner_id=?1 AND b.owner_id=?1
AND b.id=?2 AND r.chat_id=?3
ORDER BY r.id DESC LIMIT 1
`

type GetLatestOwnerBuilderRunStatusParams struct {
	OwnerID int64
	BotID   int64
	ChatID  sql.NullInt64
}

type GetLatestOwnerBuilderRunStatusRow struct {
	ID     int64
	Status string
}

func (q *Queries) GetLatestOwnerBuilderRunStatus(ctx context.Context, arg GetLatestOwnerBuilderRunStatusParams) (GetLatestOwnerBuilderRunStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestOwnerBuilderRunStatus, arg.OwnerID, arg.BotID, arg.ChatID)
	var i GetLatestOwnerBuilderRunStatusRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getOwnerInterruptedBuilderRequest = `-- name: GetOwnerInterruptedBuilderRequest :one
SELECT m.content FROM builder_runs r
JOIN builder_chats c ON c.id=r.chat_id
JOIN bots b ON b.id=c.bot_id AND b.id=r.bot_id
JOIN builder_messages m ON m.chat_id=c.id AND m.sequence=r.request_sequence AND m.role='owner'
WHERE r.id=?1 AND r.owner_id=?2 AND b.owner_id=?2
AND b.id=?3 AND c.id=?4 AND r.status='interrupted'
AND r.id=(SELECT MAX(latest.id) FROM builder_runs latest WHERE latest.chat_id=c.id)
`

type GetOwnerInterruptedBuilderRequestParams struct {
	RunID   int64
	OwnerID int64
	BotID   int64
	ChatID  int64
}

func (q *Queries) GetOwnerInterruptedBuilderRequest(ctx context.Context, arg GetOwnerInterruptedBuilderRequestParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getOwnerInterruptedBuilderRequest,
		arg.RunID,
		arg.OwnerID,
		arg.BotID,
		arg.ChatID,
	)
	var content string
	err := row.Scan(&content)
	return content, err
}

const insertOwnerBuilderCall = `-- name: InsertOwnerBuilderCall :exec
INSERT INTO builder_calls (run_id,sequence)
SELECT id,?1 FROM builder_runs WHERE id=?2 AND owner_id=?3
`

type InsertOwnerBuilderCallParams struct {
	Sequence int64
	RunID    int64
	OwnerID  int64
}

func (q *Queries) InsertOwnerBuilderCall(ctx context.Context, arg InsertOwnerBuilderCallParams) error {
	_, err := q.db.ExecContext(ctx, insertOwnerBuilderCall, arg.Sequence, arg.RunID, arg.OwnerID)
	return err
}

const interruptBuilderRuns = `-- name: InterruptBuilderRuns :exec
UPDATE builder_runs SET status='interrupted',finished_at=?1 WHERE status='running' AND lease_until <= ?2
`

type InterruptBuilderRunsParams struct {
	FinishedAt sql.NullInt64
	Now        int64
}

func (q *Queries) InterruptBuilderRuns(ctx context.Context, arg InterruptBuilderRunsParams) error {
	_, err := q.db.ExecContext(ctx, interruptBuilderRuns, arg.FinishedAt, arg.Now)
	return err
}

const listOwnerBuilderCalls = `-- name: ListOwnerBuilderCalls :many
SELECT c.run_id, c.sequence, c.input_tokens, c.output_tokens, c.total_tokens, c.cost FROM builder_calls c JOIN builder_runs r ON r.id=c.run_id
WHERE r.owner_id=?1 AND r.id=?2 ORDER BY c.sequence
`

type ListOwnerBuilderCallsParams struct {
	OwnerID int64
	RunID   int64
}

func (q *Queries) ListOwnerBuilderCalls(ctx context.Context, arg ListOwnerBuilderCallsParams) ([]BuilderCall, error) {
	rows, err := q.db.QueryContext(ctx, listOwnerBuilderCalls, arg.OwnerID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BuilderCall{}
	for rows.Next() {
		var i BuilderCall
		if err := rows.Scan(
			&i.RunID,
			&i.Sequence,
			&i.InputTokens,
			&i.OutputTokens,
			&i.TotalTokens,
			&i.Cost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnerBuilderDayCalls = `-- name: ListOwnerBuilderDayCalls :many
SELECT c.run_id, c.sequence, c.input_tokens, c.output_tokens, c.total_tokens, c.cost FROM builder_calls c JOIN builder_runs r ON r.id=c.run_id
WHERE r.owner_id=?1 AND r.day=?2 ORDER BY r.id,c.sequence
`

type ListOwnerBuilderDayCallsParams struct {
	OwnerID int64
	Day     string
}

func (q *Queries) ListOwnerBuilderDayCalls(ctx context.Context, arg ListOwnerBuilderDayCallsParams) ([]BuilderCall, error) {
	rows, err := q.db.QueryContext(ctx, listOwnerBuilderDayCalls, arg.OwnerID, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BuilderCall{}
	for rows.Next() {
		var i BuilderCall
		if err := rows.Scan(
			&i.RunID,
			&i.Sequence,
			&i.InputTokens,
			&i.OutputTokens,
			&i.TotalTokens,
			&i.Cost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnerBuilderRuns = `-- name: ListOwnerBuilderRuns :many
SELECT r.id, r.owner_id, r.bot_id, r.chat_id, r.day, r.model, r.draft_revision, r.status, r.created_at, r.lease_until, r.finished_at, r.model_calls, r.request_sequence FROM builder_runs r JOIN bots b ON b.id=r.bot_id
WHERE r.owner_id=?1 AND b.owner_id=?1 AND b.id=?2 AND r.chat_id=?3
ORDER BY r.id
`

type ListOwnerBuilderRunsParams struct {
	OwnerID int64
	BotID   int64
	ChatID  sql.NullInt64
}

func (q *Queries) ListOwnerBuilderRuns(ctx context.Context, arg ListOwnerBuilderRunsParams) ([]BuilderRun, error) {
	rows, err := q.db.QueryContext(ctx, listOwnerBuilderRuns, arg.OwnerID, arg.BotID, arg.ChatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BuilderRun{}
	for rows.Next() {
		var i BuilderRun
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.BotID,
			&i.ChatID,
			&i.Day,
			&i.Model,
			&i.DraftRevision,
			&i.Status,
			&i.CreatedAt,
			&i.LeaseUntil,
			&i.FinishedAt,
			&i.ModelCalls,
			&i.RequestSequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewOwnerBuilderRun = `-- name: RenewOwnerBuilderRun :execrows
UPDATE builder_runs SET lease_until=?1
WHERE builder_runs.id=?2 AND builder_runs.owner_id=?3 AND status='running' AND lease_until > ?4
`

type RenewOwnerBuilderRunParams struct {
	LeaseUntil int64
	RunID      int64
	OwnerID    int64
	Now        int64
}

func (q *Queries) RenewOwnerBuilderRun(ctx context.Context, arg RenewOwnerBuilderRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renewOwnerBuilderRun,
		arg.LeaseUntil,
		arg.RunID,
		arg.OwnerID,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const startOwnerBuilderCall = `-- name: StartOwnerBuilderCall :one
UPDATE builder_runs SET model_calls=model_calls+1
WHERE builder_runs.id=?1 AND builder_runs.owner_id=?2 AND status='running'
AND model_calls < ?3
AND lease_until > ?4
AND EXISTS (SELECT 1 FROM builder_chats c JOIN bots b ON b.id=c.bot_id
    WHERE c.id=builder_runs.chat_id AND b.id=builder_runs.bot_id AND b.owner_id=builder_runs.owner_id)
RETURNING model_calls
`

type StartOwnerBuilderCallParams struct {
	RunID    int64
	OwnerID  int64
	MaxCalls int64
	Now      int64
}

func (q *Queries) StartOwnerBuilderCall(ctx context.Context, arg StartOwnerBuilderCallParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, startOwnerBuilderCall,
		arg.RunID,
		arg.OwnerID,
		arg.MaxCalls,
		arg.Now,
	)
	var model_calls int64
	err := row.Scan(&model_calls)
	return model_calls, err
}
