// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery.sql

package dbgen

import (
	"context"
	"database/sql"
)

const acceptUpdate = `-- name: AcceptUpdate :execrows
INSERT INTO bot_updates (bot_id, update_id, payload, participant_id, accepted_while_paused)
SELECT ?1, ?2, ?3, ?4, bots.paused FROM bots WHERE bots.id = ?1
AND (SELECT COUNT(*) FROM bot_updates WHERE bot_id = ?1 AND complete = 0) < 1000
ON CONFLICT (bot_id, update_id) DO NOTHING
`

type AcceptUpdateParams struct {
	BotID         int64
	UpdateID      int64
	Payload       string
	ParticipantID int64
}

func (q *Queries) AcceptUpdate(ctx context.Context, arg AcceptUpdateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, acceptUpdate,
		arg.BotID,
		arg.UpdateID,
		arg.Payload,
		arg.ParticipantID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const advancePollingOffset = `-- name: AdvancePollingOffset :execrows
UPDATE bot_delivery SET polling_offset = ?3 WHERE bot_id = ?1 AND worker_nonce = ?2 AND worker_until >= unixepoch()
`

type AdvancePollingOffsetParams struct {
	BotID         int64
	WorkerNonce   string
	PollingOffset int64
}

func (q *Queries) AdvancePollingOffset(ctx context.Context, arg AdvancePollingOffsetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advancePollingOffset, arg.BotID, arg.WorkerNonce, arg.PollingOffset)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const advanceUpdateOutput = `-- name: AdvanceUpdateOutput :execrows
UPDATE bot_updates SET cursor = cursor+1, complete = ?4, attempts = 0 WHERE id = ?1 AND bot_id = ?2 AND cursor = ?3 AND complete = 0
`

type AdvanceUpdateOutputParams struct {
	ID       int64
	BotID    int64
	Cursor   int64
	Complete int64
}

func (q *Queries) AdvanceUpdateOutput(ctx context.Context, arg AdvanceUpdateOutputParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceUpdateOutput,
		arg.ID,
		arg.BotID,
		arg.Cursor,
		arg.Complete,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const beginOwnerActivation = `-- name: BeginOwnerActivation :execrows
UPDATE bot_delivery SET state = 'activating', mode = ?3, activation_nonce = ?4, activation_until = unixepoch()+30
WHERE bot_id = ?2 AND EXISTS (SELECT 1 FROM bots WHERE id = ?2 AND owner_id = ?1)
AND activation_until < unixepoch() AND worker_until < unixepoch()
`

type BeginOwnerActivationParams struct {
	OwnerID         int64
	BotID           int64
	Mode            string
	ActivationNonce string
}

func (q *Queries) BeginOwnerActivation(ctx context.Context, arg BeginOwnerActivationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, beginOwnerActivation,
		arg.OwnerID,
		arg.BotID,
		arg.Mode,
		arg.ActivationNonce,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const claimDeliveryWork = `-- name: ClaimDeliveryWork :one
UPDATE bot_delivery SET worker_nonce = ?1, worker_until = unixepoch()+60
WHERE bot_id = (
 SELECT d.bot_id FROM bot_delivery d
 WHERE d.state = 'active' AND d.mode = ?2 AND d.worker_until < unixepoch() AND d.retry_at <= unixepoch()
 AND (EXISTS (SELECT 1 FROM bot_ready_updates u WHERE u.bot_id = d.bot_id) OR d.mode = 'polling')
 ORDER BY d.retry_at, d.bot_id LIMIT 1
)
RETURNING bot_id, state, mode, encrypted_secret, activation_nonce, activation_until, worker_nonce, worker_until, retry_at, polling_offset, worker_error
`

type ClaimDeliveryWorkParams struct {
	WorkerNonce string
	Mode        string
}

func (q *Queries) ClaimDeliveryWork(ctx context.Context, arg ClaimDeliveryWorkParams) (BotDelivery, error) {
	row := q.db.QueryRowContext(ctx, claimDeliveryWork, arg.WorkerNonce, arg.Mode)
	var i BotDelivery
	err := row.Scan(
		&i.BotID,
		&i.State,
		&i.Mode,
		&i.EncryptedSecret,
		&i.ActivationNonce,
		&i.ActivationUntil,
		&i.WorkerNonce,
		&i.WorkerUntil,
		&i.RetryAt,
		&i.PollingOffset,
		&i.WorkerError,
	)
	return i, err
}

const compactCompletedUpdateOutput = `-- name: CompactCompletedUpdateOutput :execrows
UPDATE bot_updates SET output = NULL WHERE complete = 1 AND output IS NOT NULL AND received_at < unixepoch()-86400
`

func (q *Queries) CompactCompletedUpdateOutput(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, compactCompletedUpdateOutput)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeIgnoredUpdate = `-- name: CompleteIgnoredUpdate :exec
UPDATE bot_updates SET complete = 1 WHERE id = ?1 AND bot_id = ?2
`

type CompleteIgnoredUpdateParams struct {
	ID    int64
	BotID int64
}

func (q *Queries) CompleteIgnoredUpdate(ctx context.Context, arg CompleteIgnoredUpdateParams) error {
	_, err := q.db.ExecContext(ctx, completeIgnoredUpdate, arg.ID, arg.BotID)
	return err
}

const deleteExpiredParticipant = `-- name: DeleteExpiredParticipant :one
DELETE FROM bot_participants
WHERE bot_id = ?1 AND participant_id = ?2 AND expires_at <= ?3
RETURNING interaction
`

type DeleteExpiredParticipantParams struct {
	BotID         int64
	ParticipantID int64
	Now           int64
}

func (q *Queries) DeleteExpiredParticipant(ctx context.Context, arg DeleteExpiredParticipantParams) (string, error) {
	row := q.db.QueryRowContext(ctx, deleteExpiredParticipant, arg.BotID, arg.ParticipantID, arg.Now)
	var interaction string
	err := row.Scan(&interaction)
	return interaction, err
}

const deleteExpiredParticipants = `-- name: DeleteExpiredParticipants :execrows
DELETE FROM bot_participants WHERE expires_at <= ?1
`

func (q *Queries) DeleteExpiredParticipants(ctx context.Context, now int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredParticipants, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const ensureOwnerDelivery = `-- name: EnsureOwnerDelivery :execrows
INSERT INTO bot_delivery (bot_id, encrypted_secret)
SELECT id, ?3 FROM bots WHERE owner_id = ?1 AND id = ?2
ON CONFLICT (bot_id) DO NOTHING
`

type EnsureOwnerDeliveryParams struct {
	OwnerID         int64
	ID              int64
	EncryptedSecret []byte
}

func (q *Queries) EnsureOwnerDelivery(ctx context.Context, arg EnsureOwnerDeliveryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, ensureOwnerDelivery, arg.OwnerID, arg.ID, arg.EncryptedSecret)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failUndeliverableUpdate = `-- name: FailUndeliverableUpdate :exec
UPDATE bot_updates SET complete = 1, terminal_failure = 1 WHERE id = ?1 AND bot_id = ?2
`

type FailUndeliverableUpdateParams struct {
	ID    int64
	BotID int64
}

func (q *Queries) FailUndeliverableUpdate(ctx context.Context, arg FailUndeliverableUpdateParams) error {
	_, err := q.db.ExecContext(ctx, failUndeliverableUpdate, arg.ID, arg.BotID)
	return err
}

const finishOwnerActivation = `-- name: FinishOwnerActivation :execrows
UPDATE bot_delivery SET state = ?3, activation_until = 0
WHERE bot_id = ?2 AND activation_nonce = ?4
AND EXISTS (SELECT 1 FROM bots WHERE id = ?2 AND owner_id = ?1)
`

type FinishOwnerActivationParams struct {
	OwnerID         int64
	BotID           int64
	State           string
	ActivationNonce string
}

func (q *Queries) FinishOwnerActivation(ctx context.Context, arg FinishOwnerActivationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishOwnerActivation,
		arg.OwnerID,
		arg.BotID,
		arg.State,
		arg.ActivationNonce,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBotDelivery = `-- name: GetBotDelivery :one
SELECT bot_id, state, mode, encrypted_secret, activation_nonce, activation_until, worker_nonce, worker_until, retry_at, polling_offset, worker_error FROM bot_delivery WHERE bot_id = ?1
`

func (q *Queries) GetBotDelivery(ctx context.Context, botID int64) (BotDelivery, error) {
	row := q.db.QueryRowContext(ctx, getBotDelivery, botID)
	var i BotDelivery
	err := row.Scan(
		&i.BotID,
		&i.State,
		&i.Mode,
		&i.EncryptedSecret,
		&i.ActivationNonce,
		&i.ActivationUntil,
		&i.WorkerNonce,
		&i.WorkerUntil,
		&i.RetryAt,
		&i.PollingOffset,
		&i.WorkerError,
	)
	return i, err
}

const getIngressCredentials = `-- name: GetIngressCredentials :one
SELECT b.owner_id, b.telegram_id, d.encrypted_secret
FROM bots b JOIN bot_delivery d ON d.bot_id = b.id
WHERE b.id = ?1 AND d.mode = 'webhook' AND d.state IN ('activating','active','error')
`

type GetIngressCredentialsRow struct {
	OwnerID         int64
	TelegramID      int64
	EncryptedSecret []byte
}

func (q *Queries) GetIngressCredentials(ctx context.Context, id int64) (GetIngressCredentialsRow, error) {
	row := q.db.QueryRowContext(ctx, getIngressCredentials, id)
	var i GetIngressCredentialsRow
	err := row.Scan(&i.OwnerID, &i.TelegramID, &i.EncryptedSecret)
	return i, err
}

const getNextUpdate = `-- name: GetNextUpdate :one
SELECT u.id, u.bot_id, u.update_id, u.participant_id, u.payload, u.output, u.cursor, u.complete, u.attempts, u.retry_at, u.terminal_failure, u.received_at, u.accepted_while_paused FROM bot_updates u WHERE u.id IN (SELECT ready.id FROM bot_ready_updates ready WHERE ready.bot_id = ?1) ORDER BY u.update_id LIMIT 1
`

func (q *Queries) GetNextUpdate(ctx context.Context, botID int64) (BotUpdate, error) {
	row := q.db.QueryRowContext(ctx, getNextUpdate, botID)
	var i BotUpdate
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.UpdateID,
		&i.ParticipantID,
		&i.Payload,
		&i.Output,
		&i.Cursor,
		&i.Complete,
		&i.Attempts,
		&i.RetryAt,
		&i.TerminalFailure,
		&i.ReceivedAt,
		&i.AcceptedWhilePaused,
	)
	return i, err
}

const getOwnerBotCredentials = `-- name: GetOwnerBotCredentials :one
SELECT id, owner_id, telegram_id, encrypted_token FROM bots WHERE owner_id = ?1 AND id = ?2
`

type GetOwnerBotCredentialsParams struct {
	OwnerID int64
	ID      int64
}

type GetOwnerBotCredentialsRow struct {
	ID             int64
	OwnerID        int64
	TelegramID     int64
	EncryptedToken []byte
}

func (q *Queries) GetOwnerBotCredentials(ctx context.Context, arg GetOwnerBotCredentialsParams) (GetOwnerBotCredentialsRow, error) {
	row := q.db.QueryRowContext(ctx, getOwnerBotCredentials, arg.OwnerID, arg.ID)
	var i GetOwnerBotCredentialsRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.TelegramID,
		&i.EncryptedToken,
	)
	return i, err
}

const getParticipant = `-- name: GetParticipant :one
SELECT p.bot_id, p.participant_id, p.chat_id, p.publication_id, p.step_token, p.expires_at, p.interaction, p.attempt_id, v.definition FROM bot_participants p JOIN bot_publications v ON v.id = p.publication_id
WHERE p.bot_id = ?1 AND p.participant_id = ?2 AND p.expires_at > ?3
`

type GetParticipantParams struct {
	BotID         int64
	ParticipantID int64
	Now           int64
}

type GetParticipantRow struct {
	BotID         int64
	ParticipantID int64
	ChatID        int64
	PublicationID int64
	StepToken     string
	ExpiresAt     int64
	Interaction   string
	AttemptID     string
	Definition    string
}

func (q *Queries) GetParticipant(ctx context.Context, arg GetParticipantParams) (GetParticipantRow, error) {
	row := q.db.QueryRowContext(ctx, getParticipant, arg.BotID, arg.ParticipantID, arg.Now)
	var i GetParticipantRow
	err := row.Scan(
		&i.BotID,
		&i.ParticipantID,
		&i.ChatID,
		&i.PublicationID,
		&i.StepToken,
		&i.ExpiresAt,
		&i.Interaction,
		&i.AttemptID,
		&i.Definition,
	)
	return i, err
}

const getWorkerBotCredentials = `-- name: GetWorkerBotCredentials :one
SELECT b.owner_id, b.telegram_id, b.encrypted_token FROM bots b JOIN bot_delivery d ON d.bot_id = b.id
WHERE b.id = ?1 AND d.worker_nonce = ?2 AND d.worker_until >= unixepoch() AND d.state = 'active'
`

type GetWorkerBotCredentialsParams struct {
	ID          int64
	WorkerNonce string
}

type GetWorkerBotCredentialsRow struct {
	OwnerID        int64
	TelegramID     int64
	EncryptedToken []byte
}

func (q *Queries) GetWorkerBotCredentials(ctx context.Context, arg GetWorkerBotCredentialsParams) (GetWorkerBotCredentialsRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkerBotCredentials, arg.ID, arg.WorkerNonce)
	var i GetWorkerBotCredentialsRow
	err := row.Scan(&i.OwnerID, &i.TelegramID, &i.EncryptedToken)
	return i, err
}

const hasAcceptedUpdate = `-- name: HasAcceptedUpdate :one
SELECT EXISTS (SELECT 1 FROM bot_updates WHERE bot_id = ?1 AND update_id = ?2)
`

type HasAcceptedUpdateParams struct {
	BotID    int64
	UpdateID int64
}

func (q *Queries) HasAcceptedUpdate(ctx context.Context, arg HasAcceptedUpdateParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasAcceptedUpdate, arg.BotID, arg.UpdateID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const observeOwnerDelivery = `-- name: ObserveOwnerDelivery :exec
UPDATE bots SET has_webhook = ?3, pending_updates = ?4, webhook_is_piko = ?5, verified_at = unixepoch()
WHERE owner_id = ?1 AND id = ?2
`

type ObserveOwnerDeliveryParams struct {
	OwnerID        int64
	ID             int64
	HasWebhook     int64
	PendingUpdates int64
	WebhookIsPiko  int64
}

func (q *Queries) ObserveOwnerDelivery(ctx context.Context, arg ObserveOwnerDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, observeOwnerDelivery,
		arg.OwnerID,
		arg.ID,
		arg.HasWebhook,
		arg.PendingUpdates,
		arg.WebhookIsPiko,
	)
	return err
}

const recordUpdateFailure = `-- name: RecordUpdateFailure :exec
UPDATE bot_updates SET attempts = MIN(attempts+1, 10), retry_at = ?3 WHERE id = ?1 AND bot_id = ?2
`

type RecordUpdateFailureParams struct {
	ID      int64
	BotID   int64
	RetryAt int64
}

func (q *Queries) RecordUpdateFailure(ctx context.Context, arg RecordUpdateFailureParams) error {
	_, err := q.db.ExecContext(ctx, recordUpdateFailure, arg.ID, arg.BotID, arg.RetryAt)
	return err
}

const releaseDeliveryWork = `-- name: ReleaseDeliveryWork :execrows
UPDATE bot_delivery SET worker_until = 0, worker_nonce = '', retry_at = ?3, worker_error = ?4
WHERE bot_id = ?1 AND worker_nonce = ?2
`

type ReleaseDeliveryWorkParams struct {
	BotID       int64
	WorkerNonce string
	RetryAt     int64
	WorkerError int64
}

func (q *Queries) ReleaseDeliveryWork(ctx context.Context, arg ReleaseDeliveryWorkParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseDeliveryWork,
		arg.BotID,
		arg.WorkerNonce,
		arg.RetryAt,
		arg.WorkerError,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const renewDeliveryWork = `-- name: RenewDeliveryWork :execrows
UPDATE bot_delivery SET worker_until = unixepoch()+60 WHERE bot_id = ?1 AND worker_nonce = ?2 AND worker_until >= unixepoch()
`

type RenewDeliveryWorkParams struct {
	BotID       int64
	WorkerNonce string
}

func (q *Queries) RenewDeliveryWork(ctx context.Context, arg RenewDeliveryWorkParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renewDeliveryWork, arg.BotID, arg.WorkerNonce)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const saveParticipant = `-- name: SaveParticipant :exec
INSERT INTO bot_participants (bot_id, participant_id, chat_id, publication_id, step_token, interaction, attempt_id, expires_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
ON CONFLICT (bot_id, participant_id) DO UPDATE SET chat_id = excluded.chat_id,
publication_id = excluded.publication_id, step_token = excluded.step_token, interaction = excluded.interaction,
attempt_id = excluded.attempt_id, expires_at = excluded.expires_at
`

type SaveParticipantParams struct {
	BotID         int64
	ParticipantID int64
	ChatID        int64
	PublicationID int64
	StepToken     string
	Interaction   string
	AttemptID     string
	ExpiresAt     int64
}

func (q *Queries) SaveParticipant(ctx context.Context, arg SaveParticipantParams) error {
	_, err := q.db.ExecContext(ctx, saveParticipant,
		arg.BotID,
		arg.ParticipantID,
		arg.ChatID,
		arg.PublicationID,
		arg.StepToken,
		arg.Interaction,
		arg.AttemptID,
		arg.ExpiresAt,
	)
	return err
}

const stageUpdateOutput = `-- name: StageUpdateOutput :execrows
UPDATE bot_updates SET output = ?3, payload = '{}' WHERE id = ?1 AND bot_id = ?2 AND output IS NULL
`

type StageUpdateOutputParams struct {
	ID     int64
	BotID  int64
	Output sql.NullString
}

func (q *Queries) StageUpdateOutput(ctx context.Context, arg StageUpdateOutputParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, stageUpdateOutput, arg.ID, arg.BotID, arg.Output)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
